name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test Application
      run: dotnet test
    
    - name: Build Docker Image
      run: docker build --file AutoBanners/Dockerfile --tag ghcr.io/mbaksh01/auto-banners:latest .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker Image
      run: docker push ghcr.io/mbaksh01/auto-banners:latest
